### ISSUE TITLE
StartElevated throws NotSupportedException.

### ISSUE THREAD

**Issue by RaymondTracer** [falahati/UACHelper#5]
The full messaegs is:
`System.NotSupportedException: 'CreateProcess is not supported for starting an elevated process. Consider using ShellExecute by setting UseShellExecute to true.'`

**Comment by RaymondTracer** [comment]
Nevermind

**Comment by JohnKiller** [comment]
For anyone that have the same error message: it happens because .NET Framework defaulted UseShellExecute to true, while newer .NET don't. The error actually comes from a check that the library does:

https://github.com/falahati/UACHelper/blob/c279c53fb8721afc6bf252350ce7ddcb95a9cafb/UACHelper/UACHelper.cs#L594-L597

So just pass UseShellExecute = true on your ProcessStartInfo
